name: Docker build testing
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build images
      run: |
        ./tests/build-images.sh
    - name: Test images
      run: |
        ./tests/run-images.sh
  windows-2019:
    runs-on: windows-2019
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build images
      shell: powershell
      run: |
        ./tests/build-images-2019.ps1
    - name: Test images
      shell: powershell
      run: |
        ./tests/run-images-2019.ps1
  windows-2016:
    runs-on: windows-2019
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build images
      shell: powershell
      run: |
        ./tests/build-images-2016.ps1
    - name: Test images
      shell: powershell
      run: |
        ./tests/run-images-2016.ps1
